### ISSUE TITLE
Upgrading to full 'apt-get install kali-linux-full' halting on 

### ISSUE THREAD

**Issue by n0x00** [offensive-security/kali-linux-docker#9]
I'm not that well versed with Docker, but I wanted to try it as a bridge to kali from my mac

I'm not able to move any further forward on the upgrade  when I get to the output below ... 
`update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/tnameserv to provide /usr/bin/tnameserv (tnameserv) in auto mode
update-alternatives: using /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/jexec to provide /usr/bin/jexec (jexec) in auto mode
mount: permission denied
update-binfmts: warning: Couldn't mount the binfmt_misc filesystem on /proc/sys/fs/binfmt_misc.
Setting up ca-certificates-java (20140324) ..`

does anyone have any ideas ?

**Comment by steev** [comment]
How are you starting your docker container?  In order to use kali-linux-full, you'll probably need to pass some additional options to disable some of the isolations that docker has in place for using a full kali install.

That said, I was unable to replicate the issue here of it stopping at that output.  

How are you using docker on your Mac? The typical troubleshooting mantra is needed - versions of OSX, docker, and so forth.

**Comment by noxrnet** [comment]
Appears to be related to https://github.com/docker/docker/issues/18180 for Docker 1.9.1.

We are waiting on an upstream update for AUFS to fix, or downgrade as a workaround.

**Comment by steev** [comment]
Is this still an issue for you?

**Comment by steev** [comment]
Closing the issue due to lack of comment, and because the upstream issue mentioned has been closed as well.
